project:
  type: book
book:
  title: "*Statistical Rethinking* with Tidymodels"
  subtitle: "version 0.0.0.9"
  description: "This book is an attempt to re-express the code in the 2023 edition of McElreath's course, 'Statistical Rethinking.' His models are re-fit with tidymodels using brms, plots are redone with ggplot2, and the general data wrangling code predominantly follows the tidyverse style. It borrows extensively from a previous version of this book authored by Solomon Kurz."
  author: "James H Wade"
  date: 2023-01-08
  twitter-card: true
  repo-url: https://github.com/JamesHWade/statistical-rethinking-with-tidymodels
  chapters:
    - index.qmd
    - 01.qmd
    - 02.qmd
    - 99.qmd
    
bibliography: references.bib
format:
  html:
    theme: cosmo
    fig-align: "center"
    code-copy: true
    code-overflow: wrap
    citation: true
    csl: nature.csl
    
execute: 
  freeze: auto